name: build

on:
  push:
    branches: [ main ]
env:
  DOTNET_VERSION: '8.x' # The Latest .NET 8 SDK version to use
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore
      working-directory: src
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src

    - name: Test
      run: dotnet test --filter .Tests
      working-directory: src

    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
      
    - name: Deploy
      run: dotnet lambda deploy-function AwsLambda2Host
      working-directory: src/AwsLambda2Host